"""Add Price model and update Subscription

Revision ID: 11545e36d759
Revises: 1b19d7bf1f22
Create Date: 2025-11-08 14:03:30.379864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11545e36d759'
down_revision = '1b19d7bf1f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create BillingPeriod enum type if it doesn't exist (handles case where it already exists from previous attempt)
    op.execute("DO $$ BEGIN CREATE TYPE billingperiod AS ENUM ('MONTHLY', 'YEARLY'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    # Create prices table using raw SQL to avoid SQLAlchemy trying to create the enum
    op.execute("""
        CREATE TABLE prices (
            id VARCHAR(36) PRIMARY KEY,
            plan VARCHAR(50) NOT NULL,
            billing_period billingperiod NOT NULL,
            paddle_price_id VARCHAR(255) NOT NULL UNIQUE,
            paddle_product_id VARCHAR(255),
            amount INTEGER NOT NULL CHECK (amount > 0),
            currency VARCHAR(3) NOT NULL DEFAULT 'USD',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )
    """)
    # Create indexes for prices table
    op.create_index('ix_prices_billing_period', 'prices', ['billing_period'], unique=False)
    op.create_index('ix_prices_is_active', 'prices', ['is_active'], unique=False)
    op.create_index('ix_prices_paddle_price_id', 'prices', ['paddle_price_id'], unique=True)
    op.create_index('ix_prices_plan', 'prices', ['plan'], unique=False)
    op.create_index(op.f('ix_keyword_searches_enabled'), 'keyword_searches', ['enabled'], unique=False)
    op.create_index('ix_keyword_searches_user_enabled', 'keyword_searches', ['user_id', 'enabled'], unique=False)
    op.drop_index('ix_opportunities_created_at', table_name='opportunities')
    op.create_index('ix_opportunities_user_created', 'opportunities', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_opportunities_user_source', 'opportunities', ['user_id', 'source'], unique=False)
    op.create_index('ix_opportunities_user_status', 'opportunities', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_opportunity_user_source', 'opportunities', ['user_id', 'source_post_id'])
    op.create_index('ix_payments_user_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_payments_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.add_column('subscriptions', sa.Column('price_id', sa.String(length=36), nullable=True))
    # Add billing_period column using raw SQL to avoid SQLAlchemy trying to create the enum
    op.execute("ALTER TABLE subscriptions ADD COLUMN billing_period billingperiod")
    # Set default value for existing rows
    op.execute("UPDATE subscriptions SET billing_period = 'MONTHLY' WHERE billing_period IS NULL")
    # Now make it non-nullable
    op.execute("ALTER TABLE subscriptions ALTER COLUMN billing_period SET NOT NULL")
    # Convert cancel_at_period_end from VARCHAR to BOOLEAN
    # First, set default value for new column (temporary)
    op.execute("""
        ALTER TABLE subscriptions 
        ALTER COLUMN cancel_at_period_end 
        TYPE BOOLEAN 
        USING CASE 
            WHEN cancel_at_period_end = 'true' THEN TRUE 
            WHEN cancel_at_period_end = 'false' THEN FALSE 
            ELSE FALSE 
        END
    """)
    op.create_index(op.f('ix_subscriptions_billing_period'), 'subscriptions', ['billing_period'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_price_id'), 'subscriptions', ['price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'prices', ['price_id'], ['id'])
    op.create_index(op.f('ix_usage_metrics_period_start'), 'usage_metrics', ['period_start'], unique=False)
    op.create_index('ix_usage_metrics_user_type_period', 'usage_metrics', ['user_id', 'metric_type', 'period_start'], unique=False)
    op.create_unique_constraint('uq_usage_metric_user_type_period', 'usage_metrics', ['user_id', 'metric_type', 'period_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_metric_user_type_period', 'usage_metrics', type_='unique')
    op.drop_index('ix_usage_metrics_user_type_period', table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_period_start'), table_name='usage_metrics')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_price_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_period'), table_name='subscriptions')
    # Convert cancel_at_period_end from BOOLEAN back to VARCHAR
    op.execute("""
        ALTER TABLE subscriptions 
        ALTER COLUMN cancel_at_period_end 
        TYPE VARCHAR(10) 
        USING CASE 
            WHEN cancel_at_period_end = TRUE THEN 'true' 
            ELSE 'false' 
        END
    """)
    op.drop_column('subscriptions', 'billing_period')
    op.drop_column('subscriptions', 'price_id')
    op.drop_index('ix_payments_user_status', table_name='payments')
    op.drop_index('ix_payments_user_created', table_name='payments')
    op.drop_constraint('uq_opportunity_user_source', 'opportunities', type_='unique')
    op.drop_index('ix_opportunities_user_status', table_name='opportunities')
    op.drop_index('ix_opportunities_user_source', table_name='opportunities')
    op.drop_index('ix_opportunities_user_created', table_name='opportunities')
    op.create_index('ix_opportunities_created_at', 'opportunities', ['created_at'], unique=False)
    op.drop_index('ix_keyword_searches_user_enabled', table_name='keyword_searches')
    op.drop_index(op.f('ix_keyword_searches_enabled'), table_name='keyword_searches')
    op.drop_index(op.f('ix_prices_plan'), table_name='prices')
    op.drop_index(op.f('ix_prices_paddle_price_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_is_active'), table_name='prices')
    op.drop_index(op.f('ix_prices_billing_period'), table_name='prices')
    op.drop_table('prices')
    # Drop BillingPeriod enum type after all columns using it are dropped
    op.execute("DROP TYPE IF EXISTS billingperiod")
    # ### end Alembic commands ###
